config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :dashboard, :only => :show

  resources :meals, :only => [:new, :create]
  resource :daily_goal, :only => [:new, :create, :edit, :update]

  root :to => "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_goal.rb
class DailyGoal < ApplicationRecord
  belongs_to :user

  delegate :todays_meals, :to => :user

  def carbs_remaining
    carbs - todays_carbs
  end

  def fat_remaining
    fat - todays_fat
  end

  def protein_remaining
    protein - todays_protein
  end

  private

  def todays_carbs
    todays_meals.map(&:carbs).compact.sum
  end

  def todays_fat
    todays_meals.map(&:fat).compact.sum
  end

  def todays_protein
    todays_meals.map(&:protein).compact.sum
  end
end

app/models/meal.rb
class Meal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meals
  has_one :daily_goal

  def todays_meals
    meals.where("created_at BETWEEN ? AND ?", Time.current.beginning_of_day, Time.current.end_of_day)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    dashboard_path
  end
end

app/controllers/daily_goals_controller.rb
class DailyGoalsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_daily_goal, :only => [:edit, :update]

  def new
    @daily_goal = DailyGoal.new(:user => current_user)
  end
  
  def edit
    unless(@daily_goal.present?)
      # set flash
      return redirect_to new_daily_goal_path
    end
    @daily_goal = current_user.daily_goal
  end

  def create
    @daily_goal = DailyGoal.new({:user => current_user}.merge(daily_goal_params))
    if(@daily_goal.save)
      # set flash
      return redirect_to dashboard_path
    else
      # set flash
      return redirect_to new_daily_goal_path
    end
  end

  def update
    @daily_goal.update_attributes(daily_goal_params)
    if(@daily_goal.errors.any?)
      # set flash
      redirect_to edit_daily_goal_path
    else
      # set flash
      redirect_to dashboard_path
    end
  end

  private

  def daily_goal_params
    params.require(:daily_goal).permit(:fat, :carbs, :protein)
  end

  def load_daily_goal
    @daily_goal = current_user.daily_goal
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def show
    @daily_goal = current_user.daily_goal
    @meals = current_user.todays_meals
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @meal = current_user.meals.build
  end

  def create
    @meal = current_user.meals.create(meal_params)
    if(@meal.errors.any?)
      # set flash
      # redirect back to new
      flash[:error] = @meal.errors.full_messages.join
      return redirect_to new_meals_path
    else
      #set flash
      return redirect_to dashboard_path
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:fat, :carbs, :protien, :name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  FLASH_MAP = {
    'alert' => 'danger',
    'success' => 'success',
    'info' => 'info',
    'notice' => 'info',
    'warning' => 'warning'
  }
  def flash_key_to_alert(key)
    out = FLASH_MAP[key]
    raise "ERROR: invalid flash key -> #{key}" unless out.present?
    out
  end
end

app/views/daily_goals/_form.html.haml
-# Form fields for a Daily Goal
-# Locals -> <FormBuilder> f
= f.label :fat
= f.number_field :fat, :step => 0.1

%br
= f.label :carbs
= f.number_field :carbs, :step => 0.1
%br

= f.label :protein
= f.number_field :protein, :step => 0.1

%hr

app/views/daily_goals/_new.html.haml
-# partial to render a form for creating a new daily goal
-# locals <DailyGoal> daily_goal

= form_for @daily_goal, :url => daily_goal_path do |f|
  = render :partial => 'daily_goals/form', :locals => {:f => f}
  = f.submit "Set your daily goals"

app/views/daily_goals/edit.html.haml
= form_for @daily_goal do |f|
  = render :partial => 'daily_goals/form', :locals => {:f => f}
  = f.submit 'Change your daily goals'

app/views/daily_goals/new.html.haml
= render :partial => 'daily_goals/new', :locals => {:daily_goal => @daily_goal}

app/views/dashboards/_goals.html.haml
-# Partial to show macro goals for a user
-# Locals <User> user

%h3 Your daily goals -->
- if daily_goal.present?
  .daily-goals.daily-goals-carbs= daily_goal.carbs
  .daily-goals.daily-goals-carbs-remaining= daily_goal.carbs_remaining
  .daily-goals.daily-goals-fats= daily_goal.fat
  .daily-goals.daily-goals-fats-remaining= daily_goal.fat_remaining
  .daily-goals.daily-goals-protein= daily_goal.protein
  .daily-goals.daily-goals-protein-remaining= daily_goal.protein_remaining
  = link_to "Update your daily goals?", edit_daily_goal_path(daily_goal)
-else
  %h5 You have not yet set your daily goals
  = link_to "Set daily goals now", new_daily_goal_path

app/views/dashboards/show.html.haml
%h1 User dashboard

= render :partial => 'dashboards/goals', :locals => {:daily_goal => @daily_goal}

%ol
- @meals.each do |meal|
  %li 
    Meal name -->
    = meal.name

= link_to "I've eaten a meal", new_meal_path

app/views/layouts/_flash.html.haml
- if flash.any?
  - flash.keys.each do |flash_key|
    %div{:class => "alert alert-#{flash_key_to_alert(flash_key)} alert-dismissable flash #{flash_key}"}
      = flash[flash_key]
  %li.nav-item

app/views/layouts/_nav.html.haml
%nav.nav.navbar.navbar-toggleable-md.navbar-light.bg-faded
  %button.navbar-toggler{:type=>"button", :data => {:toggle=>"collapse", :target=>"#keto-trac-navbar"}, :aria_controls=>"keto-trac-navbar", :aria_expanded=>"false", :aria_label=>"Toggle navigation"}
    %span.navbar-toggler-icon

  </button>
  .collapse.navbar-collapse{:id => 'keto-trac-navbar'}
    = link_to 'KetoTrac', root_url, :class => 'navbar-brand'
    %ul.navbar-nav.ml-auto
      = render :partial => "layouts/nav/user_auth"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KetoTrac</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%-#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <div class="container-fluid">
      <%= render 'layouts/nav' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/nav/_user_auth.html.haml
- if user_signed_in?
  %li.nav-item
    = link_to 'sign out', destroy_user_session_path, :method => :delete, :class => 'nav-link'
- else
  %li.nav-item
    = link_to 'sign in', new_user_session_path, :class => 'nav-link'
  %li.nav-item
    = link_to 'sign up', new_user_registration_path, :class => 'nav-link'

app/views/meals/_form.html.haml
-# Form fields for a Meal
-# Locals -> <FormBuilder> f
= f.label :fat
= f.number_field :fat, :step => 0.1

%br
= f.label :carbs
= f.number_field :carbs, :step => 0.1
%br

= f.label :protein
= f.number_field :protein, :step => 0.1

%br

= f.label :name
= f.text_field :name

%hr

app/views/meals/_new.html.haml
-# Form to create a new meal
-# Locals -> <Meal> meal
= form_for meal do |f|
  = render :partial => 'meals/form', :locals => {:f => f}
  = f.submit "Create"

app/views/meals/new.html.haml
= render :partial => 'meals/new', :locals => {:meal => @meal}

app/views/welcome/index.html.haml
%h1 Welcome to keto tracker!!